title: <p align="center"> Rahul R </p>
logo: /assets/img/Profile.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahul-nair-326487b7/">LinkedIn</a> |
  <a href="https://github.com/RR-Nair">GitHub</a>
 
  <br>  
  I'm working on Implementation Consultant,Machine learning related problems.
  
  
  
  
  <br>
  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
